# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anscape < Formula
  desc "Bridge local commands to Anscape cloud agents"
  homepage "https://anscape.com"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anscapeai/anscape-releases/releases/download/v0.1.3/anscape_0.1.3_darwin_amd64.tar.gz"
      sha256 "aa26125da6437b60b11788ecca6fa069599619fd82b021ee7bf5aaf41ce29211"

      define_method(:install) do
        bin.install "anscape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anscapeai/anscape-releases/releases/download/v0.1.3/anscape_0.1.3_darwin_arm64.tar.gz"
      sha256 "84ec4269f48c68f3d852f98d0f68da5e16d7f0833523cd1935475ef177bc5b8f"

      define_method(:install) do
        bin.install "anscape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anscapeai/anscape-releases/releases/download/v0.1.3/anscape_0.1.3_linux_amd64.tar.gz"
      sha256 "340d0698470f5cbd01400b07428345333d5e895c6e10507c52172783c0182513"
      define_method(:install) do
        bin.install "anscape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anscapeai/anscape-releases/releases/download/v0.1.3/anscape_0.1.3_linux_arm64.tar.gz"
      sha256 "91fdcce6d79511ca1807fea785835807a2bc33ebf53d6575a65ff0ffd4e3e0d4"
      define_method(:install) do
        bin.install "anscape"
      end
    end
  end

  test do
    system "#{bin}/anscape", "--version"
  end
end
