# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anscape < Formula
  desc "Bridge local commands to Anscape cloud agents"
  homepage "https://anscape.com"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anscapeai/anscape-releases/releases/download/v1.1.1/anscape_1.1.1_darwin_amd64.tar.gz"
      sha256 "0c30d8c879a48638355c673d59f5fcb33341d3346b5cd0976f7da9d4052faa31"

      define_method(:install) do
        bin.install "anscape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anscapeai/anscape-releases/releases/download/v1.1.1/anscape_1.1.1_darwin_arm64.tar.gz"
      sha256 "01363da2ea3bf2cbeadcbf29b9de5c607b2c03026bce6a7ce2751bbbcc7065ad"

      define_method(:install) do
        bin.install "anscape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anscapeai/anscape-releases/releases/download/v1.1.1/anscape_1.1.1_linux_amd64.tar.gz"
      sha256 "6186a57650fcbeb1098eb9741bdfcc86c62dad69426a37312f041970dd2c830d"
      define_method(:install) do
        bin.install "anscape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anscapeai/anscape-releases/releases/download/v1.1.1/anscape_1.1.1_linux_arm64.tar.gz"
      sha256 "6d2c7c4d4057cb6d8a5262e18a4c9fbf5f0a69806bac97388d676688e5267e35"
      define_method(:install) do
        bin.install "anscape"
      end
    end
  end

  test do
    system "#{bin}/anscape", "--version"
  end
end
