# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anscape < Formula
  desc "Bridge local commands to Anscape cloud agents"
  homepage "https://anscape.com"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anscapeai/anscape-releases/releases/download/v0.1.2/anscape_0.1.2_darwin_amd64.tar.gz"
      sha256 "368243c1babdf44f25c6f552bd916f8cd0340f2f98cc7d68cf6d6b8a54fcc35e"

      define_method(:install) do
        bin.install "anscape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anscapeai/anscape-releases/releases/download/v0.1.2/anscape_0.1.2_darwin_arm64.tar.gz"
      sha256 "2b9e2ffefd43fb7f93f2c8274dcf180560d4c3be4540907c4c69f1577ab0ab73"

      define_method(:install) do
        bin.install "anscape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anscapeai/anscape-releases/releases/download/v0.1.2/anscape_0.1.2_linux_amd64.tar.gz"
      sha256 "cc00bce309aea64bc2ce91164121df68b24c7663fd158941508277fe05c90771"
      define_method(:install) do
        bin.install "anscape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anscapeai/anscape-releases/releases/download/v0.1.2/anscape_0.1.2_linux_arm64.tar.gz"
      sha256 "4f55fd5111dcd8e2b09eb68b744c84e0fe257f7bc6e6852dbebb3de73c32f297"
      define_method(:install) do
        bin.install "anscape"
      end
    end
  end

  test do
    system "#{bin}/anscape", "--version"
  end
end
